# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/opsidian-freecad',
                'doc_host': 'https://panukorn17.github.io',
                'git_url': 'https://github.com/panukorn17/opsidian-freecad',
                'lib_path': 'opsidian_freecad'},
  'syms': {'opsidian_freecad.core': {'opsidian_freecad.core.foo': ('core.html#foo', 'opsidian_freecad/core.py')}}}
